Algoritmo "Aula 2"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aula de laço de repetição(repita)
// Autor(a)    : Gleison Almeida de Freitas
// Data atual  : 28/09/2022
Var
// Seção de Declarações das variáveis 
contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
repita
escreval("Sem braço curto")
contadora<- contadora+1
ate contadora>7

Fimalgoritmo